version: '3.5'

services:
  tap-web:
    # Direct Repo
    image: ${GITHUB_REGISTRY}/${GITHUB_USERNAME}/${IMAGE_REPO_NAME}:${IMAGE_TAG}
    volumes:
      # PROD: Bind Volume method on source folder 
      -  ./source/:/var/www/source/

      # Bind volume for user data: Need always on #
      - ./files/session/:/var/www/html/writable/session/
      - ./files/uploads/:/var/www/html/writable/uploads/
      - ./files/logs/:/var/www/html/writable/logs/
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - composer_installation
      - npm_installation
    restart: unless-stopped

  #######################
  # Install depedencies #
  #######################
  # Install composer
  composer_installation:
    # container_name: composer_installation
    image: composer
    volumes:
      - ./source/:/app/
    command: composer install --ignore-platform-reqs

  # Install npm
  npm_installation:
    # container_name: npm_installation
    image: node:12.16.1-slim
    working_dir: /app
    volumes:
      - ./source/public/:/app/
    command: bash -c "npm install"