version: '3.5'

services:
  tap-web:
    build:
      context: .
      dockerfile: DockerfileDevelopment
      args:
        - GITHUB_REGISTRY=${GITHUB_REGISTRY}
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - IMAGE_REPO_NAME=${IMAGE_REPO_NAME}
        - IMAGE_TAG=${IMAGE_TAG}
    volumes:
      # DEV: Bind Volume method direct to container directory
      -  ./source/:/var/www/html/

      # Bind volume for user data: Need always on #
      - ./files/session/:/var/www/html/writable/session/
      - ./files/uploads/:/var/www/html/writable/uploads/
      - ./files/logs/:/var/www/html/writable/logs/
    ports:
      - ${APPLICATION_PORT}:8080
    depends_on:
      - composer_installation
      - npm_installation
    restart: unless-stopped

  #######################
  # Install depedencies #
  #######################
  # Install composer
  composer_installation:
    # container_name: composer_installation
    image: composer
    volumes:
      - ./source/:/app/
    command: composer install --ignore-platform-reqs

  # Install npm
  npm_installation:
    # container_name: npm_installation
    image: node:12.16.1-slim
    working_dir: /app
    volumes:
      - ./source/public/:/app/
    command: bash -c "npm install"